spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd HH:mm"
  flyway:
    enabled:true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:file:~/blogs
    username: sa
    password:
    driverClassName: org.h2.Driver
logging:
  level:
    lt:
      techin: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: INFO

application:
  version: 0.2
